version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - echo `pwd`
      - chmod +x ./gradlew  # Ensure gradlew has execute permissions
      - ./gradlew dependencies
  pre_build:
    commands:
      - echo Pre-build phase...
      - chmod +x ./gradlew
      - ./gradlew clean
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build artifacts are located in `build/libs/`
artifacts:
  files:
    - 'runner-service/build/libs/runner-service-1.0.war'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'
    
